sudo: false

notifications:
  email: false

language: go

go:
  - 1.10.x
  - 1.11.x

env:
  global:
  - GOARCH=amd64
  - TEST_HOST=127.0.0.1

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - "sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf"
  - "sudo service postgresql restart 10"

install:
  - mkdir -p $GOPATH/src/upper.io
  - mv $PWD $GOPATH/src/upper.io/bond
  - cd $GOPATH/src/upper.io/bond
  - go get -v -t -d ./...
  - export TRAVIS_BUILD_DIR=$GOPATH/src/upper.io/bond

script:
  - make test
